# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ec9a5097e1dfcbdf2b64d568a5d55be7baaa74ebea55d69a11b7fcd5b4af50db36dac9438bfdebbf8eea3240ffb28cdb2451e3ec382d634a41189a345e0b4c

test:
  secret_key_base: 28918627af5606f419d26bd3fb35bac18824d0757da11f11b71cfb08e9cb66db16ebbc2915365a3bdf21224d534f4d95238bdb245a8749453663c0bd709bea74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
